// Generated by scripts/generate-ai-issue-catalogs.cjs. Do not edit by hand.

export const ISSUE_CATALOG_VERSION = "toronto-311-ai-issue-catalog-v2";
export const PHOTO_LABEL_TAXONOMY_VERSION = "photo-label-taxonomy-v3";

/** The current taxonomy version, then older ones that app builds may still send. */
export const SUPPORTED_PHOTO_LABEL_TAXONOMY_VERSIONS: readonly string[] = [
  "photo-label-taxonomy-v3"
];
